# Generated by Django 3.1.5 on 2021-01-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeySkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000, null=True)),
                ('key_skills', models.ManyToManyField(to='workshop_system.KeySkill')),
            ],
        ),
    ]
