# Generated by Django 3.1.5 on 2021-01-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_system', '0002_jobtitle_professionalstandart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalstandart',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
